config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  devise_for :users

  # Defines the root path route ("/")
  get "about", to: "about#index"

  # get "signup", to: "registrations#new"
  # post "signup", to: "registrations#create"

  # get  "login", to: "sessions#new"
  # post "login", to: "sessions#create"
  # delete "logout", to: "sessions#destroy"

  get "users/:id", to: "profiles#show", as: "view_profile"
  # get "profile/:id/edit", to: "profiles#edit", as: "edit_profile"
  # patch "profile/:id", to: "profiles#update", as: "update_profile"

  # get "password/reset", to: "password_resets#new", as: "forgot_password"
  # post "password/reset", to: "password_resets#create", as: "create_password"
  # get "password/reset/edit", to: "password_resets#edit", as: "edit_password"
  # patch "password/reset/edit", to: "password_resets#update", as: "update_password"

  resources :products

  resources :bookings do
    member do
      resources :payments, only: [ :new, :create ]

      get "print", to: "bookings#print", as: "print"
    end
  end

  root to: "main#index"
end

app/views/shared/_currency.html.erb
<%= eur(amount) %>

app/views/shared/_flash.html.erb
<div class="d-flex justify-content-center my-4">
  <% if flash[:notice] %>
  <div class="alert alert-success" role="alert" role="alert" data-mdb-color="success" data-mdb-alert-init="" id="success_flash" data-mdb-alert-initialized="true">
    <%= flash[:notice] %>
  </div>
  <% end %>

  <% if flash[:alert] %>
  <div class="alert alert-dismissible fade show alert-danger" role="alert" data-mdb-color="danger" data-mdb-alert-init="" id="danger_flash" data-mdb-alert-initialized="true">
    <%= flash[:alert] %>
  </div>
  <% end %>

  <% if flash[:info] %>
  <div class="alert alert-info" role="alert" role="alert" data-mdb-color="info" data-mdb-alert-init="" id="info_flash" data-mdb-alert-initialized="true">
    <%= flash[:info] %>
  </div>
  <% end %>
</div>

app/views/shared/_form_errors.html.erb
<% if object&.errors&.any? %>
<div class="alert alert-danger p-3" role="alert">
  <ul class="list-unstyled mb-0">
    <% object.errors.full_messages.each do |message| %>
    <li class="mb-1">
      <i class="fas fa-times-circle me-2 text-danger"></i>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button data-mdb-collapse-init class="navbar-toggler" type="button" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <%= image_tag "torqly_logo.png", alt: "Torqly Logo", class: "rounded", height: 40 %>
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if is_admin? %>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">

      <% if !is_logged_in? %>
      <% if !current_page?(new_user_session_path) && !current_page?(new_user_registration_path) %>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-secondary me-3" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary me-3" %>
      <% end %>
      <% else %>
      <span class="me-3">Hello, <%= current_user.name %></span>
      <div class="dropdown">
        <button class="nav-link dropdown-toggle" id="navbarProfileMenu" type="button" aria-expanded="false" data-controller="mdb-dropdown" data-mdb-dropdown-init data-turbo-permanent>
          <i class="fas fa-user"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarProfileMenu">
          <li>
            <%= link_to "My profile", view_profile_path(current_user), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item"  %>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to log out?" }, class: "dropdown-item" %>
          </li>
        </ul>
      </div>
    </div>
    <% end %>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->